Ensure delete_store gets called if volume exists
[#145019413]

diff --git a/jobs/grootfs/templates/bin/utils.erb b/jobs/grootfs/templates/bin/utils.erb
--- a/jobs/grootfs/templates/bin/utils.erb
+++ b/jobs/grootfs/templates/bin/utils.erb
@@ -68,13 +68,15 @@ delete_store() {
   local store_path=$2
   local volume_file=$3
 
-  # Allow grootfs delete-store and umount to fail, because we could
-  # have an malformed store.
-  grootfs --config $config_path delete-store || true
-  umount --force $store_path || true
+  if [ -d "$store_path" ] || [ -f "$volume_file ]; then
+    # Allow grootfs delete-store and umount to fail, because we could
+    # have an malformed store.
+    grootfs --config $config_path delete-store || true
+    umount --force $store_path || true
 
-  # Ensure that the store is deleted, or fail
-  rm -rf $store_path
+    # Ensure that the store is deleted, or fail
+    rm -rf $store_path
 
-  rm -rf $volume_file
+    rm -rf $volume_file
+  fi
 }
