Allow external log device configuration for XFS driver
* Add external_logdevice_size_in_mb property

[#145187705]

Signed-off-by: Tiago Scolari <tscolari@pivotal.io>

diff --git a/jobs/grootfs/templates/bin/utils.erb b/jobs/grootfs/templates/bin/utils.erb
--- a/jobs/grootfs/templates/bin/utils.erb
+++ b/jobs/grootfs/templates/bin/utils.erb
@@ -57,43 +57,6 @@ setup_unprivileged_store() {
   chmod 0700 $store_path
 }
 
-delete_store() {
-  local config_path=$1
-  local store_path=$2
-  local volume_file=$3
-
-  if [ -d "$store_path" ] || [ -f "$volume_file" ]; then
-    # Allow grootfs delete-store and umount to fail, because we could
-    # have an malformed store.
-    grootfs --config $config_path delete-store || true
-    try_umount $store_path || true
-
-    # Ensure that the store is deleted, or fail
-    rm -rf $store_path
-
-    rm -rf $volume_file
-  fi
-}
-
-try_umount() {
-  local mount_point=$1
-
-  if ! mountpoint $mount_point
-  then
-    return
-  fi
-
-  local n=0
-   until [ $n -ge 5 ]
-   do
-      umount $mount_point && return
-      n=$[$n+1]
-      sleep 2
-   done
-
-   echo "Failed to unmount $mount_point"
-}
-
 unprivileged_root_mapping() {
   maximus_uid=$(/var/vcap/packages/idmapper/bin/maximus)
   echo -n "0:${maximus_uid}:1"
@@ -110,4 +73,19 @@ volume_size() {
   <% else %>
   echo "<%= p('grootfs.store_size_bytes') %>"
   <% end %>
+}
+
+delete_store() {
+  local config_path=$1
+  local store_path=$2
+  local volume_file=$3
+
+  # Allow grootfs delete-store and umount to fail, because we could
+  # have an malformed store.
+  grootfs --config $config_path delete-store || true
+  umount --force $store_path || true
+
+  # Ensure that the store is deleted, or fail
+  rm -rf $store_path
+  rm -f $volume_file
 }
